# Configuration file template
# Modify the values below as deemed nescessary
# See the documentation for more informations
# ------------------------------------------------------------------------------

# Workflow control
# ----------------

# Path to the output directory, will be created if it doesnÂ´t exist
workdir: .tests/integration
# Path to folder containingt he raw data files in .fastq.gz format
fastq_folder: data
# path to metadata file
metadata: data/metadata.tsv

# Additional parameters
# ---------------------
# max threads per parallel job
max_threads_sample: 1

# fastq naming scheme for BfR create_sample_sheet script ('illumina', 'ncbi', flex')
fastq_naming: illumina
