# Integration test config
# ----------------------


workdir: .tests/integration
# Path to folder containingt he raw data files in .fastq.gz format
fastq_folder: data
# path to metadata file
metadata: data/metadata.tsv

# max threads per parallel job
max_threads_sample: 1

# fastq naming scheme for BfR create_sample_sheet script ('illumina', 'ncbi', 'dot', 'flex')
fastq_naming: flex
